### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect. -  error on windows 

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [AbhinavRobinson/tauri-screen-recorder#1]
I'm getting the following error on windows. 

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }', src\screenshot.rs:56:59`

How I can fix it?

**Comment by aniketbiprojit** [comment]
Try adding relative or absolute path or directly replace with `string "C:\\Users\\<username>\\Desktop\\data.png"`

**Comment by AbhinavRobinson** [comment]
I don't have a windows machine, please feel free to fix and create a PR :))
